version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server:20.3
    container_name: clickhouse
    hostname: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8123:8123
      - 9000:9000