version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  clickhouse:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse
    hostname: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8123:8123
      - 9000:9000