version: "2.1"
services:
  jobmanager:
    image: flink:1.10.2
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    networks: 
      - flinknet
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager1:
    image: flink:1.10.2
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    networks: 
      - flinknet
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager2:
    image: flink:1.10.2
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    networks: 
      - flinknet
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

networks: 
  flinknet:
    name: flinknet
    driver: bridge
