- name: copy config files
  with_items: "{{ items }}"
  copy:
    src: "{{ item }}"
    dest: "~/service/clickhouse/{{ item }}"
- name: generate macros.xml
  template:
    src: macros.xml.j2
    dest: ~/service/clickhouse/macros.xml
- name: start docker compose
  shell: docker-compose up -d chdir=~/service/clickhouse