version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  clickhouse1:
    image: yandex/clickhouse-server:20.3
    container_name: clickhouse1
    hostname: clickhouse1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./node1/config.xml:/etc/clickhouse-server/config.xml
      - ./node1/config.d:/etc/clickhouse-server/config.d
      - ./node1/copier:/etc/clickhouse-server/copier

  clickhouse2:
    image: yandex/clickhouse-server:20.3
    container_name: clickhouse2
    hostname: clickhouse2
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./node2/config.xml:/etc/clickhouse-server/config.xml
      - ./node2/config.d:/etc/clickhouse-server/config.d

  clickhouse3:
    image: yandex/clickhouse-server:20.3
    container_name: clickhouse3
    hostname: clickhouse3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./node3/config.xml:/etc/clickhouse-server/config.xml
      - ./node3/config.d:/etc/clickhouse-server/config.d