version: "3.8"

services:
  master:
    image: alluxio/alluxio:2.8.1
    container_name: master
    hostname: master
    command: master
    environment:
      - ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage
    volumes:
      - ./alluxio_ufs:/opt/alluxio/underFSStorage
    ports:
      - 19999:19999
      - 19998:19998

  worker:
    image: alluxio/alluxio:2.8.1
    container_name: worker
    hostname: worker
    command: worker
    environment:
      - ALLUXIO_JAVA_OPTS=-Dalluxio.worker.ramdisk.size=64M -Dalluxio.master.hostname=master
    volumes:
      - ./alluxio_ufs:/opt/alluxio/underFSStorage
    ports:
      - 29999:29999
      - 30000:30000
