{
 "title": "ClickHouse Queries",
 "description": "Helps to visualize most frequent, slowest, failed queries.\r\nShows queries rate per second, table with last queries",
 "tags": [
  "clickhouse",
  "performance"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "5m" },
   { "name": "type", "label": "type", "query": "1,2,3,4" },
   { "name": "top", "label": "top elements", "query": "5,10,15,20,25,30" },
   {
    "name": "user",
    "label": "initial user",
    "query": "select distinct initial_user from system.query_log where event_date >= today()-3 and event_time > toDateTime(today()-3)"
   },
   { "name": "query_type", "label": "query type", "query": "all,select,insert" },
   { "name": "except_db", "label": "except db", "query": "null,system" },
   { "name": "except_child_query", "label": "except child query", "query": "0,1" },
   { "name": "slow_query_duration_ms", "label": "slow query duration ms", "query": "50" }
  ]
 },
 "panels": [
  {
   "title": "Types",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "1 - successful start of query execution\n\n2 - successful end of query execution\n\n3 - exception before start of query execution\n\n4 - exception while query execution"
   }
  },
  {
   "title": "Top $top request's rate by type: $type; user: $user; query type: $query_type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rateColumns</font>(<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"navajowhite\">cityHash64</font>(query) <font color=\"darkorange\">global</font> <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">cityHash64</font>(<font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>)) <font color=\"darkorange\">AS</font> h<br />    <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />    <font color=\"darkorange\">WHERE</font><br />        <font color=\"darkcyan\">$timeFilter</font><br />        <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />        <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />        <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br />    <font color=\"darkorange\">GROUP BY</font> h<br />    <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font>() <font color=\"darkorange\">desc</font><br />    <font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>)<br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "$rateColumns(\n    substring(query,  1,  45) AS query,\n    count() c)\nFROM $table\nWHERE\n    cityHash64(query) global in (\n    SELECT cityHash64(substring(query,  1,  45)) AS h\n    FROM $table\n    WHERE\n        $timeFilter\n        AND type in ($type)\n        AND initial_user in ($user)\n        AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\n    GROUP BY h\n    ORDER BY count() desc\n    LIMIT $top)\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND is_initial_query in ($except_child_query)\n    AND has(databases, '$except_db') = 0\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))",
     "rawQuery": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM (SELECT t, groupArray((query, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t, substring(query, 1, 45) AS query, count() c FROM system.query_log\nWHERE event_date >= toDate(1639020138) AND event_date <= toDate(1639021938) AND event_time >= toDateTime(1639020138) AND event_time <= toDateTime(1639021938) AND\n    cityHash64(query) global in (\n    SELECT cityHash64(substring(query,  1,  45)) AS h\n    FROM system.query_log\n    WHERE\n        event_date >= toDate(1639020138) AND event_date <= toDate(1639021938) AND event_time >= toDateTime(1639020138) AND event_time <= toDateTime(1639021938)\n        AND type in (1,2,3,4)\n        AND initial_user in ('default','')\n        AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))\n    GROUP BY h\n    ORDER BY count() desc\n    LIMIT 5)\n    AND type in (1,2,3,4)\n    AND initial_user in ('default','')\n    AND is_initial_query in (1)\n    AND has(databases, 'null') = 0\n    AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) GROUP BY t, query ORDER BY t, query) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top slow queries by type: $type; user: $user; query type: $query_type",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    substring(query,  1,  50) AS query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM $table\nWHERE\n    $timeFilter\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND has(databases, '$except_db') = 0\n    AND query_duration_ms >= $slow_query_duration_ms\n    AND is_initial_query in ($except_child_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY query\nORDER BY duration desc\nLIMIT $top",
     "rawQuery": "SELECT\n    substring(query,  1,  50) AS query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1639020147) AND event_date <= toDate(1639021947) AND event_time >= toDateTime(1639020147) AND event_time <= toDateTime(1639021947)\n    AND type in (1,2,3,4)\n    AND initial_user in ('default','')\n    AND has(databases, 'null') = 0\n    AND query_duration_ms >= 50\n    AND is_initial_query in (1)\n    AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))\nGROUP BY query\nORDER BY duration desc\nLIMIT 5",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top memory consumers by type: $type; user: $user; query type: $query_type",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    substring(query,  1,  50) AS query,\n    avg(memory_usage) usage,\n    count() count\nFROM $table\nWHERE\n    $timeFilter\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND has(databases, '$except_db') = 0\n    AND is_initial_query in ($except_child_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT $top",
     "rawQuery": "SELECT\n    substring(query,  1,  50) AS query,\n    avg(memory_usage) usage,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1639020156) AND event_date <= toDate(1639021956) AND event_time >= toDateTime(1639020156) AND event_time <= toDateTime(1639021956)\n    AND type in (1,2,3,4)\n    AND initial_user in ('default','')\n    AND has(databases, 'null') = 0\n    AND is_initial_query in (1)\n    AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))\nGROUP BY query\nORDER BY usage desc\nLIMIT 5",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top failed queries by user: $user; query type: failed",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"darkorange\">type</font>,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"cornflowerblue\">3</font>,<font color=\"cornflowerblue\">4</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font><br />    query,<br />    <font color=\"darkorange\">type</font><br /><font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    substring(query,  1,  50) AS query,\n    type,\n    count() count\nFROM $table\nWHERE\n    $timeFilter\n    AND type in (3,4)\n    AND initial_user in ($user)\n    AND has(databases, '$except_db') = 0\n    AND is_initial_query in ($except_child_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY\n    query,\n    type\nORDER BY count desc\nLIMIT $top",
     "rawQuery": "SELECT\n    substring(query,  1,  50) AS query,\n    type,\n    count() count\nFROM system.query_log\nWHERE\n    event_date >= toDate(1639020162) AND event_date <= toDate(1639021962) AND event_time >= toDateTime(1639020162) AND event_time <= toDateTime(1639021962)\n    AND type in (3,4)\n    AND initial_user in ('default','')\n    AND has(databases, 'null') = 0\n    AND is_initial_query in (1)\n    AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))\nGROUP BY\n    query,\n    type\nORDER BY count desc\nLIMIT 5",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Reqs/s by type: $type; user: $user; query type: $query_type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "$rate(count() c)\nFROM $table\nwhere  type in ($type)\n    AND initial_user in ($user)\n    AND has(databases, '$except_db') = 0\n    AND is_initial_query in ($except_child_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))",
     "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t, count() c FROM system.query_log\nWHERE event_date >= toDate(1639020167) AND event_date <= toDate(1639021967) AND event_time >= toDateTime(1639020167) AND event_time <= toDateTime(1639021967) AND  type in (1,2,3,4)\n    AND initial_user in ('default','')\n    AND has(databases, 'null') = 0\n    AND is_initial_query in (1)\n    AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Query duration by type: $type; user: $user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms)  select_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br />    <font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'select'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms)  select_duration\nFROM $table\nWHERE\n    $timeFilter\n    AND type = 2\n    AND has(databases, '$except_db') = 0\n    AND is_initial_query in ($except_child_query)\n    AND positionCaseInsensitive(query,  'select') = 1\n    AND initial_user in ($user)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    avg(query_duration_ms)  select_duration\nFROM system.query_log\nWHERE\n    event_date >= toDate(1639020181) AND event_date <= toDate(1639021981) AND event_time >= toDateTime(1639020181) AND event_time <= toDateTime(1639021981)\n    AND type = 2\n    AND has(databases, 'null') = 0\n    AND is_initial_query in (1)\n    AND positionCaseInsensitive(query,  'select') = 1\n    AND initial_user in ('default','')\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) insert_duration\nFROM $table\nWHERE\n    $timeFilter\n    AND type = 2\n    AND positionCaseInsensitive(query,  'insert into') = 1\n    AND is_initial_query in ($except_child_query)\n    AND initial_user in ($user)\n    AND has(databases, '$except_db') = 0\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(event_time), 2) * 2) * 1000 as t,\n    avg(query_duration_ms) insert_duration\nFROM system.query_log\nWHERE\n    event_date >= toDate(1639020181) AND event_date <= toDate(1639021981) AND event_time >= toDateTime(1639020181) AND event_time <= toDateTime(1639021981)\n    AND type = 2\n    AND positionCaseInsensitive(query,  'insert into') = 1\n    AND is_initial_query in (1)\n    AND initial_user in ('default','')\n    AND has(databases, 'null') = 0\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Query log by type: $type; user: $user; query type: $query_type",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM $table\nWHERE $timeFilter\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND has(databases, '$except_db') = 0\n    AND is_initial_query in ($except_child_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nORDER BY event_time DESC\nLIMIT 1000",
     "rawQuery": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM system.query_log\nWHERE event_date >= toDate(1639020188) AND event_date <= toDate(1639021988) AND event_time >= toDateTime(1639020188) AND event_time <= toDateTime(1639021988)\n    AND type in (1,2,3,4)\n    AND initial_user in ('default','')\n    AND has(databases, 'null') = 0\n    AND is_initial_query in (1)\n    AND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))\nORDER BY event_time DESC\nLIMIT 1000",
     "round": "0s",
     "table": "query_log"
    }
   ]
  }
 ]
}