{
 "title": "ClickHouse_InterServer_Metrics",
 "description": "ClickHouse internal exporter metrics",
 "tags": [
  "ClickHouse",
  "DB"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_Uptime, instance)"
    }
   },
   {
    "name": "export_instance",
    "label": "Einstance",
    "query": {
     "query": "label_values(clickhouse_tcp_connection, instance)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(clickhouse_table_parts_count, database)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(clickhouse_table_parts_count, table)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Baisc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of connections to TCP server (clients with native interface), also included server-server distributed query connections. \nNumber of connections to HTTP server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-tcp"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-http"
    },
    {
     "expr": "ClickHouseMetrics_InterserverConnection{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-interserver"
    },
    {
     "expr": "ClickHouseMetrics_MySQLConnection{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-mysql"
    },
    {
     "expr": "ClickHouseMetrics_PostgreSQLConnection{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-postgre sql"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queries",
   "type": "graph",
   "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time(irate(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[2m])[$__rate_interval:15s])",
     "legendFormat": "{{instance}}-queries"
    },
    {
     "expr": "max_over_time(irate(ClickHouseProfileEvents_FailedQuery{instance=~\"$instance\"}[2m])[$__rate_interval:15s])",
     "legendFormat": "{{instance}}-failed queries"
    }
   ]
  },
  {
   "title": "Query spend (avg)",
   "type": "graph",
   "description": "Avg queries latencies",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_QueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-all"
    },
    {
     "expr": "increase(ClickHouseProfileEvents_InsertQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-insert"
    },
    {
     "expr": "increase(ClickHouseProfileEvents_SelectQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-select"
    }
   ]
  },
  {
   "title": "SELECT queries",
   "type": "graph",
   "description": "Same as Queries, but only for SELECT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}-all"
    },
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedSelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}-failed"
    }
   ]
  },
  {
   "title": "INSERT queries",
   "type": "graph",
   "description": "Same as Queries, but only for INSERT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}-all"
    },
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedInsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}-failed"
    }
   ]
  },
  {
   "title": "Query preemted and memory limit",
   "type": "graph",
   "description": "Number of queries that are stopped and waiting due to 'priority' setting.\nNumber of times when memory limit exceeded for query.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseMetrics_QueryPreempted{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}-preemted"
    },
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}-memory-limit"
    }
   ]
  },
  {
   "title": "Insert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inserted rows",
     "type": "graph",
     "description": "Number of rows INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_InsertedRows[5m])"
      }
     ]
    },
    {
     "title": "Inserted bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Delayed inserts query",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rejected insert blocks",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a MergeTree table was rejected with 'Too many parts' exception due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_RejectedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Delayed inserts blocks (avg)",
     "type": "graph",
     "description": "Total number of milliseconds spent while the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_DelayedInsertsMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Select", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Parts",
   "type": "graph",
   "description": "Number of data parts selected to read from a MergeTree table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedParts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-adjacent ranges",
   "type": "graph",
   "description": "Number of (non-adjacent) ranges in all data parts selected to read from a MergeTree table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRanges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Marks",
   "type": "graph",
   "description": "Number of marks (index granules) selected to read from a MergeTree table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedMarks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "description": "Number of rows SELECTed from all tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "description": "Number of bytes (uncompressed; for columns as they stored in memory) SELECTed from all tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Reduce process thread times",
   "type": "graph",
   "description": "由于读取速度慢而降低查询处理线程数的次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBackoff{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow reads times",
   "type": "graph",
   "description": "Number of reads from a file that were slow. This indicate system overload. Thresholds are controlled by read_backoff_* settings.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SlowRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "lseek",
     "type": "graph",
     "description": "Number of times the 'lseek' function was called.\nlseek 函数的作用是设置读取文件的起始读取位置",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Seek{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "description": "Number of files opened",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FileOpen{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read from FD",
     "type": "graph",
     "description": "Number of reads (read/pread) from a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}-all"
      },
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}-failed"
      }
     ]
    },
    {
     "title": "Write to FD",
     "type": "graph",
     "description": "Number of writes (write/pwrite) to a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}-all"
      },
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteFailed{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}-failed"
      }
     ]
    },
    {
     "title": "Read bytes from FD",
     "type": "graph",
     "description": "Number of bytes read from file descriptors. If the file is compressed, this will show the compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": " {{instance}}"
      }
     ]
    },
    {
     "title": "Write bytes to FD",
     "type": "graph",
     "description": "Number of bytes written to file descriptors. If the file is compressed, this will show compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read compressed bytes",
     "type": "graph",
     "description": "*``compressed``: Number of bytes (the number of bytes before decompression) read from compressed sources (files, network).\n\n*``uncompressed``: Number of uncompressed bytes (the number of bytes after decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}-compressed"
      },
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}-uncompressed"
      }
     ]
    },
    {
     "title": "Read compressed blocks",
     "type": "graph",
     "description": "Number of compressed blocks (the blocks of data that are compressed independent of each other) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
       "legendFormat": "{{instance}}-peaks"
      }
     ]
    }
   ]
  },
  { "title": "Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Abnormal replica",
   "type": "graph",
   "description": "Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReadonlyReplica",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicated part fetches instead of merged",
   "type": "graph",
   "description": "Number of times we prefer to download already merged part from replica of ReplicatedMergeTree table instead of performing a merge ourself (usually we prefer doing a merge ourself to save network traffic). This happens when we have not all source parts to perform a merge or when the data part is old enough.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicated part fetches",
   "type": "graph",
   "description": "Number of times a data part was downloaded from replica of a ReplicatedMergeTree table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}-failed"
    }
   ]
  },
  {
   "title": "Replicated part data loss",
   "type": "graph",
   "description": "Number of times a data part that we wanted doesn't exist on any replica (even on replicas that are offline right now). That data parts are definitely lost. This is normal due to asynchronous replication (if quorum inserts were not enabled), when the replica on which the data part was written was failed and when it became online after fail it doesn't contain that data part.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedDataLoss{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicated part successfully merges times",
   "type": "graph",
   "description": "Number of times data parts of ReplicatedMergeTree tables were successfully merged.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartMerges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Merge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Merge times",
   "type": "graph",
   "description": "Number of launched background merges.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merged read rows",
   "type": "graph",
   "description": "Rows read for background merges. This is the number of rows before merge.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merge read uncompressed bytes",
   "type": "graph",
   "description": "Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merge duration (avg)",
   "type": "graph",
   "description": "Avg merge duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_MergesTimeMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree insert rows",
   "type": "graph",
   "description": "Number of rows INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree insert blocks",
   "type": "graph",
   "description": "Number of blocks INSERTed to MergeTree tables. Each block forms a data part of level zero.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree insert uncompressed bytes",
   "type": "graph",
   "description": "Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree insert compressed bytes",
   "type": "graph",
   "description": "Bytes written to filesystem for data INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk reserved space for merges",
   "type": "graph",
   "description": "Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_DiskSpaceReservedForMerge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Uncompressed Cache Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheHits{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uncompressed Cache Misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheMisses{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mark Cache Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheHits{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mark Cache Misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheMisses{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Parts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Temporary",
   "type": "graph",
   "description": "The part is generating now, it is not in data_parts list.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsTemporary{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pre commited",
   "type": "graph",
   "description": "The part is in data_parts, but not used for SELECTs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsPreCommitted{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commited",
   "type": "graph",
   "description": "The part is in data_parts, but not used for SELECTs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsCommitted{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outdated",
   "type": "graph",
   "description": "Not active data part, but could be used by only current SELECTs, could be deleted after SELECTs finishes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsOutdated{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deleting",
   "type": "graph",
   "description": "Not active data part with identity refcounter, it is deleting right now by a cleaner.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsDeleting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Delete on destroy",
   "type": "graph",
   "description": "Part was moved to another disk and should be deleted in own destructor.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsDeleteOnDestroy{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wide part count",
   "type": "graph",
   "description": "Wide 类型存储的 parts 数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ClickHouseMetrics_PartsWide", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Compact part count",
   "type": "graph",
   "description": "Compac 类型存储的 parts 数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ClickHouseMetrics_PartsCompact", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "In-memory",
   "type": "graph",
   "description": "In-memory parts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsInMemory{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 } },
  {
   "title": "Table Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "clickhouse_table_parts_bytes{database=~\"$database\", table=~\"$table\"}",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table Partition Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_table_parts_count{database=~\"$database\", table=~\"$table\"}",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table Row Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_table_parts_rows{database=~\"$database\", table=~\"$table\"}",
     "legendFormat": "{{database}}.{{table}}"
    }
   ]
  },
  { "title": "Distributed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 } },
  {
   "title": "Send",
   "type": "graph",
   "description": "Number of connections to remote servers sending data that was INSERTed into Distributed tables. Both synchronous and asynchronous mode.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_DistributedSend{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Files to insert",
   "type": "graph",
   "description": "Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_DistributedFilesToInsert{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed delayed inserts",
   "type": "graph",
   "description": "Number of times the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed rejected inserts",
   "type": "graph",
   "description": "Number of times the INSERT of a block to a Distributed table was rejected with 'Too many bytes' exception due to high number of pending bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedRejectedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed delayed inserts blocks (avg)",
   "type": "graph",
   "description": "Total number of milliseconds spent while the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_DistributedDelayedInsertsMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DistributedDelayedInserts{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed connection fail try",
   "type": "graph",
   "description": "Total count when distributed connection fails with retry",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailTry{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed connection fail at all",
   "type": "graph",
   "description": "Total count when distributed connection fails after all retries finished",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed sync insertation timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedSyncInsertionTimeoutExceeded{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Background pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 242 } },
  {
   "title": "BackgroundPool task",
   "type": "graph",
   "description": "Number of active tasks in BackgroundProcessingPool (merges, mutations, or replication queue bookkeeping)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundPoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackgroundFetchesPool task",
   "type": "graph",
   "description": "Number of active tasks in BackgroundFetchesPool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundFetchesPoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackgroundMovePool task",
   "type": "graph",
   "description": "Number of active tasks in BackgroundProcessingPool for moves",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundMovePoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackgroundSchedulePool task",
   "type": "graph",
   "description": "Number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 251 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundSchedulePoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackgroundBufferFlushSchedulePool task",
   "type": "graph",
   "description": "Number of active tasks in BackgroundBufferFlushSchedulePool. This pool is used for periodic Buffer flushes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundBufferFlushSchedulePoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackgroundDistributedSchedulePool task",
   "type": "graph",
   "description": "Number of active tasks in BackgroundDistributedSchedulePool. This pool is used for distributed sends that is done in background.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundDistributedSchedulePoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackgroundMessageBrokerSchedulePool task",
   "type": "graph",
   "description": "Number of active tasks in BackgroundProcessingPool for message streaming",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 267 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundMessageBrokerSchedulePoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "Init",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperInit{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 276 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperTransactions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "List",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 284 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperList{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Create",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 284 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperCreate{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Remove",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 292 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperRemove{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exists",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 292 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperExists{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Get",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 300 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperGet{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 300 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperSet{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Multi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 308 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperMulti{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 308 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperCheck{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Close",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 316 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperClose{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Watch response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 316 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperWatchResponse{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 324 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperUserExceptions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hardware Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 324 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperHardwareExceptions{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 332 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesReceived{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 332 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesSent{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "description": "Number of sessions (connections) to ZooKeeper. Should be no more than one, because using more than one connection to ZooKeeper may lead to bugs due to lack of linearizability (stale reads) that ZooKeeper consistency model allows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 340 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperSession{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ephemeral Node",
   "type": "graph",
   "description": "Number of ephemeral nodes hold in ZooKeeper.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 340 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_EphemeralNode{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Watches",
   "type": "graph",
   "description": "Number of watches (event subscriptions) in ZooKeeper.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 348 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperWatch{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Number of requests to ZooKeeper in fly.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 348 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperRequest{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Remove ephemeral node failed",
   "type": "graph",
   "description": "Number of times an error happened while trying to remove ephemeral node. This is not an issue, because our implementation of ZooKeeper library guarantee that the session will expire and the node will be removed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 356 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_CannotRemoveEphemeralNode{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] )",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}