version: '3'
services: 
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: 'bitnami/kafka:2.8.1'
    container_name: broker
    hostname: broker
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-exporter:
    image: bitnami/kafka-exporter:1.6.0
    container_name: kafka-exporter
    hostname: kafka-exporter
    command: 
      - --kafka.server=broker:9092
    depends_on:
      - broker
    ports:
      - 9308:9308

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./conf:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.1.5
    container_name: grafana
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000


  