version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    privileged: true
    environment:
      - discovery.type=single-node
      #- network.publish_host=172.16.12.23
      - indices.fielddata.cache.size=60%
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    hostname: elasticsearch
    networks:
      - esnet
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    privileged: true
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    hostname: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - esnet
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"

  elastalert:
    image: bitsensor/elastalert:latest
    container_name: elastalert
    hostname: elastalert
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./elastalert/conf/config.yaml:/opt/elastalert/config.yaml
      - ./elastalert/conf/config.json:/opt/elastalert-server/config/config.json
      - ./elastalert/rules:/opt/elastalert/rules
      - ./elastalert/rule_templates:/opt/elastalert/rule_templates
      - ./elastalert/conf/smtp_auth.yaml:/opt/elastalert/smtp_auth.yaml
    networks:
      - esnet
    ports:
      - "3031:3031"

networks:
  esnet:
    name: esnet
    driver: bridge
