version: '3'
services:

  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  clickhouse1:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse1
    hostname: clickhouse1
    ports:
      - 9001:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node1/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node1/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node1/config.d:/etc/clickhouse-server/config.d
      - ./conf/node1/users.d:/etc/clickhouse-server/users.d
      - ./conf/node1/copier:/etc/clickhouse-server/copier

  clickhouse2:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse2
    hostname: clickhouse2
    ports:
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node2/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node2/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node2/config.d:/etc/clickhouse-server/config.d
      - ./conf/node2/users.d:/etc/clickhouse-server/users.d