{
 "title": "ClickHouse Queries",
 "description": "Helps to visualize most frequent, slowest, failed queries.Shows queries rate per second, table with last queries",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "initial user",
    "query": "select distinct initial_user from system.query_log where event_date >= today()-3 and event_time > toDateTime(today()-3)"
   },
   { "name": "type", "label": "type", "query": "1,2,3,4" },
   { "name": "top", "label": "top elements", "query": "5,10,15,20,25,30" },
   {
    "name": "contain_db",
    "label": "contain db",
    "query": "select database from system.databases where name not in ('INFORMATION_SCHEMA','information_schema')"
   },
   { "name": "query_type", "label": "query type", "query": "all,select,insert" },
   { "name": "slow_query_duration_ms", "label": "slow query duration ms", "query": "50" },
   { "name": "is_init_query", "label": "is init query", "query": "0,1" },
   { "name": "table", "label": "table", "query": "system.query_log_all" },
   { "name": "constant_select", "label": "constant select", "query": "select" }
  ]
 },
 "panels": [
  {
   "title": "Types",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "1 - successful start of query execution\n\n2 - successful end of query execution\n\n3 - exception before start of query execution\n\n4 - exception while query execution"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reqs total by type: $type; user: $user; query type: $query_type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeInterval(event_time) as time,  \n  count(query_id) total \nFROM $table\nWHERE \n  $__timeFilter(event_time)\n  AND type in ($type)\n  AND initial_user in ($user)\n  AND hasAny(databases, [$contain_db]) = 1\n  AND is_initial_query in ($is_init_query)\n  AND('$query_type' = 'all' or(positionCaseInsensitive(query, '$query_type') >= 1))\nGROUP BY time \nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "AVG Query duration by user: $user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeInterval(event_time) as time,\n    avg(query_duration_ms)  select_duration\nFROM $table\nWHERE\n    $__timeFilter(event_time)\n    AND type = 2\n    AND hasAny(databases, [$contain_db]) = 1\n    AND is_initial_query in ($is_init_query)\n    AND positionCaseInsensitive(query,  trim('select')) >= 1\n    AND initial_user in ($user)\nGROUP BY time\nORDER BY time asc"
    },
    {
     "rawSql": "SELECT\n    $__timeInterval(event_time) as time,\n    avg(query_duration_ms)  insert_duration\nFROM $table\nWHERE\n    $__timeFilter(event_time)\n    AND type = 2\n    AND has(databases, '$except_db') = 0\n    AND is_initial_query in ($is_init_query)\n    AND positionCaseInsensitive(query,  trim('insert into')) = 1\n    AND initial_user in ($user)\nGROUP BY time\nORDER BY time asc"
    }
   ]
  },
  {
   "title": "Top 50 slow Query by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    event_time,\n    user,\n    databases,\n    tables,\n    query_duration_ms duration,\n    memory_usage,\n    read_rows,\n    read_bytes,\n    if(exception!='', 'fail', 'success') result,\n    query\nFROM $table\nWHERE $__timeFilter(event_time)\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND hasAny(databases, [$contain_db]) = 1\n    AND is_initial_query in ($is_init_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') >= 1))\nORDER BY duration desc, memory_usage DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Top slow queries by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    query AS query,\n    avg(query_duration_ms) avg_duration,\n    count() count\nFROM $table\nWHERE\n    $__timeFilter(event_time)\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND hasAny(databases, [$contain_db]) = 1\n    AND query_duration_ms >= $slow_query_duration_ms\n    AND is_initial_query in ($is_init_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') >= 1))\nGROUP BY query\nORDER BY avg_duration desc\nLIMIT $top"
    }
   ]
  },
  {
   "title": "Top memory usage by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    query,\n    avg(memory_usage) avg_usage,\n    count() count\nFROM $table\nWHERE\n    $__timeFilter(event_time)\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND hasAny(databases, [$contain_db]) = 1\n    AND is_initial_query in ($is_init_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') >= 1))\nGROUP BY query\nORDER BY avg_usage desc\nLIMIT $top"
    }
   ]
  },
  {
   "title": "Top failed queries by user: $user; query type: failed",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    query,\n    type,\n    count() count\nFROM $table\nWHERE\n    $__timeFilter(event_time)\n    AND type in (3,4)\n    AND initial_user in ($user)\n    AND hasAny(databases, [$contain_db]) = 1\n    AND is_initial_query in ($is_init_query)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') >= 1))\nGROUP BY\n    query,\n    type\nORDER BY count desc\nLIMIT $top"
    }
   ]
  }
 ]
}