version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: bitnami/kafka:2.8.1
    container_name: broker
    hostname: broker
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://broker:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  redis:
    image: redis
    container_name: redis
    hostname: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  clickhouse1:
    image: yandex/clickhouse-server:21.8.14.5
    container_name: clickhouse1
    hostname: clickhouse1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8121:8123
      - 9001:9000
    depends_on:
      - zookeeper

  clickhouse2:
    image: yandex/clickhouse-server:21.8.14.5
    container_name: clickhouse2
    hostname: clickhouse2
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8122:8123
      - 9002:9000
    depends_on:
      - zookeeper
      - clickhouse1